version: '3.8'

services:
  # order-service:
  #   build: ./order-microservice
  #   ports:
  #     - "7000:7000"  # Expose your Node.js app on port 7000
  #   environment:
  #     DATABASE_URL: postgresql://postgres:root@db:5432/order_db  # Use 'db' as the hostname for PostgreSQL
  #     RABBITMQ_URL: amqp://rabbitmq:5672  # Use 'rabbitmq' as the hostname for RabbitMQ
  #   depends_on:
  #     - db
  #     - rabbitmq
  user-service:
    build: ./user-microservice
    ports:
      - "5000:5000" 
    environment:
      DATABASE_URL: postgresql://postgres:root@userdb:5432/pusers  # Use 'db' as the hostname for PostgreSQL
      RABBITMQ_URL: amqp://rabbitmq:5672  # Use 'rabbitmq' as the hostname for RabbitMQ
    depends_on:
      - userdb
      - rabbitmq


  # db:
  #   image: postgres:latest  # Use the latest PostgreSQL image
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres  # Set the PostgreSQL user
  #     POSTGRES_PASSWORD: root   # Set the PostgreSQL password
  #     POSTGRES_DB: order_db     # Set the name of the database
  #   ports:
  #     - "5434:5432"  # Expose PostgreSQL on port 5432
    



  userdb:
    image: postgres:latest  # Use the latest PostgreSQL image
    restart: always
    environment:
      POSTGRES_USER: postgres  # Set the PostgreSQL user
      POSTGRES_PASSWORD: root   # Set the PostgreSQL password
      POSTGRES_DB: pusers    # Set the name of the database
    ports:
      - "5432:5432"  # Expose PostgreSQL on port 5432

  rabbitmq:
    image: rabbitmq:3-management  # RabbitMQ with the management plugin
    restart: always
    ports:
      - "5672:5672"      # RabbitMQ default port
      - "15672:15672"    # Management UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest  # Default username
      RABBITMQ_DEFAULT_PASS: guest  # Default password


  prometheus:
    image: prom/prometheus:latest
  
    ports:
      - "9090:9090"